### ISSUE TITLE
Fatal error that crashes UE5.1.1

### ISSUE THREAD

**Issue by LiveWaffle** [Tectors/JsonAsAsset#10]
Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectGlobals.cpp] [Line: 920] Attempted to create a package with name containing double slashes. PackageName: //Character_SubsurfaceProfile
 
UnrealEditor_CoreUObject
UnrealEditor_JsonAsAsset!FAssetUtilities::CreateAssetPackage() [P:\JsonAsAsset\JsonAsAsset\HostProject\Plugins\JsonAsAsset\Source\JsonAsAsset\Private\Utilities\AssetUtilities.cpp:79]
UnrealEditor_JsonAsAsset!IImporter::ImportReference() [P:\JsonAsAsset\JsonAsAsset\HostProject\Plugins\JsonAsAsset\Source\JsonAsAsset\Private\Importers\Importer.cpp:128]
UnrealEditor_JsonAsAsset!FJsonAsAssetModule::PluginButtonClicked() [P:\JsonAsAsset\JsonAsAsset\HostProject\Plugins\JsonAsAsset\Source\JsonAsAsset\Private\JsonAsAsset.cpp:73]
UnrealEditor_JsonAsAsset!TBaseRawMethodDelegateInstance<0,FJsonAsAssetModule,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [P:\Wahm\UE_5.1\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:475]
UnrealEditor_Slate

This happens when you try importing Character_SubsurfaceProfile.json

**Comment by 0xZylox** [comment]
![image](https://user-images.githubusercontent.com/76428709/233814662-013e7f33-210e-4091-ae1e-29a177b6ef28.png)

As I can see on your ss from fortnite porting your path is invalid as its \ but it needs to use /
Example:
 > F:/Github/FModel/FModel/bin/Release/net6.0-windows/win-x64/Output
select the path via the ... and not paste the path in from explorer
