### ISSUE TITLE
Error when importing Materials

### ISSUE THREAD

**Issue by AeptaX** [Tectors/JsonAsAsset#16]
If needed, this is my json file (https://www.mediafire.com/file/prlvur4q5h57rwi/M_Cube_Purple_Dudebro.json/file)
Trying to import the .o file results in an error. Importing the normal json (the link above) has the following in the crash report: 

Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectGlobals.cpp] [Line: 920] Attempted to create a package with name containing double slashes. PackageName: //M_Cube_Purple_Dudebro

UnrealEditor_CoreUObject
UnrealEditor_JsonAsAsset!FAssetUtilities::CreateAssetPackage() [P:\JsonAsAsset\JsonAsAsset\HostProject\Plugins\JsonAsAsset\Source\JsonAsAsset\Private\Utilities\AssetUtilities.cpp:79]
UnrealEditor_JsonAsAsset!IImporter::ImportReference() [P:\JsonAsAsset\JsonAsAsset\HostProject\Plugins\JsonAsAsset\Source\JsonAsAsset\Private\Importers\Importer.cpp:128]
UnrealEditor_JsonAsAsset!FJsonAsAssetModule::PluginButtonClicked() [P:\JsonAsAsset\JsonAsAsset\HostProject\Plugins\JsonAsAsset\Source\JsonAsAsset\Private\JsonAsAsset.cpp:73]
UnrealEditor_JsonAsAsset!TBaseRawMethodDelegateInstance<0,FJsonAsAssetModule,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [P:\Wahm\UE_5.1\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:475]

I also have a image of my settings.
![image](https://user-images.githubusercontent.com/79169958/236022205-d13790a8-c096-45f7-9096-9d947bc78545.png)

**Comment by Tectors** [comment]
Show me what's inside of your Export folder please.

**Comment by Tectors** [comment]
Please reply

**Comment by AeptaX** [comment]
Sorry, had alot to do these past few days so I couldn't reply. This is what is inside my Export folder.
![image](https://user-images.githubusercontent.com/79169958/236623405-e08084ea-a418-4fd6-935a-215ebcee885b.png)

**Comment by Tectors** [comment]
It has to be in the Exports folder.
