### ISSUE TITLE
'JsonAsAsset' is Incompatible

### ISSUE THREAD

**Issue by Chem-pro** [Tectors/JsonAsAsset#19]
I downloaded UE5.2 to test "JsonAsAsset 1.2.0 (5.2)" but I am getting this error.
The 'JsonAsAsset' plugin was designed for build 5.1.0. Attempt to load it anyway?
at the end I am getting 
LuxorGame could not be compiled. Try rebuilding from source manually.

**Comment by Tectors** [comment]
compile the plugin, its for 5.1
