### ISSUE TITLE
Unspecified Function after importing material/function

### ISSUE THREAD

**Issue by Pengu1ns** [Tectors/JsonAsAsset#20]
Some materials fail to compile when you import them because material functions inside other functions don't get imported. It works great if you import the missing functions manually but it would be really nice to be able to import one file and have everything imported.

**Comment by GMatrixGames** [comment]
If you use local fetch, that happens.

**Comment by Tectors** [comment]
We've already thought about this! Please learn more about Local Fetch (API that supplies JsonAsAsset with textures/material functions and more!):

#### *Local Fetch Tutorial:* https://github.com/Tectors/JsonAsAsset/tree/main#3-setting-up-local-fetch

**Comment by Pengu1ns** [comment]
I was using Local Fetch previously, the problem was sometimes it would fail to import a few material functions, but I haven't run into the problem since thankfully.
