### ISSUE TITLE
UE5.1 Crash when import Materials or Material Functions 

### ISSUE THREAD

**Issue by AMMAREN** [Tectors/JsonAsAsset#5]
I am ues:-
 JsonAsAsset plugin #v1.1
 Fortnite Game 
 FModel v 4.4.2.0
===========================

The is the Crash reporter
===========================
((
LoginId:a3e4056e436aa4e743fcf2b3f9e9100d
EpicAccountId:e64b8477bdd24982a008d7cb56393667

Assertion failed: InShadingModel < MSM_NUM [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Classes\Engine\EngineTypes.h] [Line: 638]

UnrealEditor_Engine
UnrealEditor_JsonAsAsset!UMaterialImporter::ImportData() [E:\00-Unreal Engine Project\2030\Uiana_511\Plugins\JsonAsAsset\Source\JsonAsAsset\Private\Importers\MaterialImporter.cpp:94]
UnrealEditor_JsonAsAsset!IImporter::ImportReference() [E:\00-Unreal Engine Project\2030\Uiana_511\Plugins\JsonAsAsset\Source\JsonAsAsset\Private\Importers\Importer.cpp:151]
UnrealEditor_JsonAsAsset!FJsonAsAssetModule::PluginButtonClicked() [E:\00-Unreal Engine Project\2030\Uiana_511\Plugins\JsonAsAsset\Source\JsonAsAsset\Private\JsonAsAsset.cpp:63]
UnrealEditor_JsonAsAsset!TBaseRawMethodDelegateInstance<0,FJsonAsAssetModule,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:424]
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
user32
user32
UnrealEditor_ApplicationCore
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll 
   )))

![jsonAsAsset_P](https://user-images.githubusercontent.com/7099115/233538306-deb1ee20-13ad-450a-ace8-fead96f95949.png)

![jsonAsAsset](https://user-images.githubusercontent.com/7099115/233538352-061d7cd4-7396-406a-a5cc-bf4f13bebb71.png)

**Comment by Tectors** [comment]
my guy you can't just import a huge master material without their textures and referencing material functions

**Comment by Tectors** [comment]
send the json

**Comment by AMMAREN** [comment]
Ok ... this is json
https://mega.nz/folder/ENcHWQIT#d6KV9HeDLmKNs6SJo0gpRw

**Comment by Tectors** [comment]
There is no material data in that asset. It's obvious why it gave a error.

**Comment by AMMAREN** [comment]
I see......
But what version FModel you are using and.... Can you send or give me any name of material you already checked and work
So i can know which version of FModel work with plugin

**Comment by Tectors** [comment]
> I see...... But what version FModel you are using and.... Can you send or give me any name of material you already checked and work So i can know which version of FModel work with plugin

1. You understand that you can't just import a material without adding the references right? You're missing all the textures.
2. I am using the developer version of FModel, which can be found on the FModel Github page on branch dev

**Comment by AMMAREN** [comment]
OK it seem FModel branch dev is better and all asset types is working fine... But still Crash when import Material Functions or Materials like before.

This step i do maybe incorrect .... can you check it please.
===================================================

1)- Make a new UE5.1 project ((blank - C++) selected))
2)- put plugin in project
3)- Export all textures from Fmodel then import it to UE5.1 project.
4)- Export all textures. Material Functions. Material Master. Material Instance. and other asset types in json files inside folder (FModel\Output\Exports)
5) Then i use the plugin

I Have a question what you mean ((adding the references right)) is the there any special references Material Node i need to put it in plugin or in UE5.1 project?

Note:-
==========
I check this plugin in more than 10 games the same problem (all Asset Types is working except Material Functions or Materials)

For example :-
Fortnite	
VALORANT	
Tekken 7	
Ascendant One	
Tower of Fantasy	
Soul Clibur VI
TOGETHER VR

**Comment by 0xZylox** [comment]
You need to modify Fmodel so it combines .o.uasset json with the normal one also it will only work on games that have editoronlydata (.o.uasset files) which is only in fortnite if im not mistaken.
