### ISSUE TITLE
Add NiagaraParameterCollection

### ISSUE THREAD

**Issue by 0xZylox** [Tectors/JsonAsAsset#7]
NiagaraParameterCollection

It basically just uses the material one as base but the values could have been modified

![image](https://user-images.githubusercontent.com/76428709/233804009-353aad54-7102-4d70-956f-75ad5e96b58a.png)

[NPC_Nexus2.zip](https://github.com/Tectors/JsonAsAsset/files/11302203/NPC_Nexus2.zip)

**Comment by Tectors** [comment]
> [NiagaraParameterCollection at EpicGames/UnrealEngine](https://github.com/EpicGames/UnrealEngine/blob/46544fa5e0aa9e6740c19b44b0628b72e7bbd5ce/Engine/Plugins/FX/Niagara/Source/Niagara/Classes/NiagaraParameterCollection.h)

see if you can add it yourself, shouldn't be hard
